# Generated by Django 4.2.6 on 2023-11-08 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "verbose_name": "Dispositivo",
                "verbose_name_plural": "Dispositivos",
            },
        ),
        migrations.AlterModelOptions(
            name="environment",
            options={"verbose_name": "Ambiente", "verbose_name_plural": "Ambientes"},
        ),
        migrations.RenameField(
            model_name="device",
            old_name="create",
            new_name="update",
        ),
        migrations.RenameField(
            model_name="environment",
            old_name="create",
            new_name="update",
        ),
    ]
